### ISSUE TITLE
Implement Playback Controls for Timeline

### ISSUE THREAD

**Issue by CallumJHays** [QUT-Motorsport/QUTMS_ConfigApp#29]
This will be the basis of the telemetry interface.
![image](https://user-images.githubusercontent.com/13251689/75204836-c001cb80-57bd-11ea-9da4-1cacce2bf7e8.png)

It might be difficult to implement the draggable yellow timeline bar, as it requires some funky CSS to be overlayed over the timeline component. If you're not confident with your CSS / React skills then try just putting a slider beneath the timeline for now:
https://ant.design/components/slider/

The Timeline Component should be edited to achieve this:
https://github.com/QUT-Motorsport/QUTMS_ConfigApp/blob/ecd281f8cb98b37cfa7a727ab0415421484190aa/react/components/Timeline.tsx#L19

Just the controls need to be implemented for now. Next steps will be getting data highlighting in the charts based off the current playback time.

**Comment by CallumJHays** [comment]
Next steps: actuating the react components for telemetry designed by @J-Hoskin 
![image](https://user-images.githubusercontent.com/13251689/75618511-266e5b80-5bbb-11ea-8e37-60ec8a91dcfd.png)

Example of similar interface in i2 pro:
![telemetry](https://user-images.githubusercontent.com/13251689/75618494-d55e6780-5bba-11ea-95a0-071a0e4a67b1.gif)

**Comment by Leptoflux** [comment]
Mostly implemented can use some improvements but otherwise done
