### ISSUE TITLE
Add conda environment.yml file to simplify development installation

### ISSUE THREAD

**Issue by CallumJHays** [QUT-Motorsport/QUTMS_ConfigApp#8]
Particular focus on making sure the jupyterlab installation with all widgets & ROS integration is achievable in a single command

**Comment by CallumJHays** [comment]
The electron app bundler may also require integrating this installation method.

**Comment by LDwhoRU** [comment]
Test this on Monday on a fresh install?

**Comment by CallumJHays** [comment]
The file is currently empty 😂

I think I'll be able to get one of the software team guys to do this today.

**Comment by CallumJHays** [comment]
Donezo
